name: Installer

on:
  push:
    branches:
      - '*'

jobs:
  run-command:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          iex (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/WindEntertainment/wpm/master/install.ps1')

      - name: Run on macOS
        if: runner.os == 'macOS'
        shell: 'bash'
        run: |
          bash <(curl -s https://raw.githubusercontent.com/WindEntertainment/wpm/master/install.bash)
          wpm -h

      - name: Run on Linux
        if: runner.os == 'Linux'
        shell: 'bash'
        run: |
          bash <(curl -s https://raw.githubusercontent.com/WindEntertainment/wpm/master/install.bash)
          wpm -h
