name: Python CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Build
        shell: bash
        run: |
          python ./build.py

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get the short commit hash
        id: commit
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create or update "latest" tag
        run: |
          git tag -f latest
          git push -f origin latest

      - name: Delete existing release (if any)
        run: |
          gh release delete $sha --yes || echo "No existing release to delete"

      - name: Create a new release using GitHub CLI
        run: |
          gh release create $sha \
            --title "Release $sha" \
            --notes "Release for commit $sha" \
            /home/runner/work/wpm/wpm/source.zip

      - name: Update "latest" release
        run: |
          gh release edit latest --tag $sha
