name: prod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Build
        shell: bash
        run: |
          python ./build.py

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get the commit sha
        id: commit
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create a new release
        run: |
          gh release delete $sha --yes || echo "No existing release to delete"
          gh release create $sha --title "Release $sha" --generate-notes --latest /home/runner/work/wpm/wpm/source.zip
