name: Python CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Build
        shell: bash
        run: |
          python ./build.py

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get the short commit hash
        id: commit
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Create or update "latest" tag
        run: |
          git tag -f latest
          git push -f origin latest

      - name: Create a new release using GitHub CLI
        run: |
          gh release create ${{ steps.commit.outputs.sha }} \
            --title "Release ${{ steps.commit.outputs.sha }}" \
            --notes "Release for commit ${{ steps.commit.outputs.sha }}" \
            /home/runner/work/wpm/wpm/source.zip

      # - name: Get upload URL
      #   id: get_upload_url
      #   run: |
      #     upload_url=$(curl -L \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/${{github.repository}}/releases/latest | jq -r '.upload_url'
      #     )
      #     echo $upload_url
      #     echo ::set-output name=upload_url::$upload_url

      # - name: Get Release ID
      #   id: get_id
      #   run: |
      #     release_id=$(curl -L \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/${{github.repository}}/releases/latest | jq -r '.id'
      #     )
      #     echo $release_id
      #     echo ::set-output name=release_id::$release_id

      # - name: Get Asset Url
      #   id: get_asset_url
      #   run: |
      #     asset_url=$(curl -L \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/${{github.repository}}/releases/${{ steps.get_id.outputs.release_id }}/assets | jq -r '.[0].url'
      #     )
      #     echo $asset_url
      #     echo ::set-output name=asset_url::$asset_url

      # - name: Remove release asset
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     curl -X DELETE \
      #       -H "Authorization: token $GITHUB_TOKEN" \
      #       ${{ steps.get_asset_url.outputs.asset_url }}

      # - name: Upload Release Asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
      #     asset_path: /home/runner/work/wpm/wpm/source.zip
      #     asset_name: source.zip
      #     asset_content_type: application/zip
